apiVersion: v1
kind: ConfigMap
metadata:
  name: pelias-json-configmap
data:
  pelias.json: |
    {
      "esclient": {
        "apiVersion": "2.4",
        "hosts": [{
          "host": "elasticsearch-service"
        }]
      },
      "api": {
        "services": {
          "pip": {
            "url": "http://pelias-pip-service:3102/"
          }
        }
      },
      "acceptance-tests": {
        "endpoints": {
          "local": "http://pelias-api-service:3100/v1/"
        }
      },
      "schema": {
        "indexName": "pelias"
      },
      "logger": {
        "level": "debug",
        "timestamp": true
      },
      "imports": {
        "geonames": {
          "datapath": "/data/geonames",
          "countryCode": "mx"
        },
        "openaddresses": {
          "datapath": "/data/openaddresses",
          "files": ["us/ma/city_of_boston.csv"]
        },
        "openstreetmap": {
          "download": [{
              "sourceURL": "https://s3.amazonaws.com/metro-extracts.mapzen.com/boston_massachusetts.osm.pbf"
          }],
          "datapath": "/data/osm",
          "import": [{
            "filename": "boston_massachusetts.osm.pbf"
          }]
        },
        "polyline": {
          "datapath": "/data/polyline",
          "files": ["planet.polylines"]
        },
        "whosonfirst": {
          "importVenues": false,
          "datapath": "/data/whosonfirst/"
        }
      }
    }
