# override this to use external elasticsearch
elasticsearchHost: "elasticsearch-service"

# Whether the API service should be externally accessible
# Set this to true if you want to, for example on AWS, set up an ELB for the API
externalAPIService: false

# Whether the dashboard should be set up
dashboardEnabled: false

placeholderHost: "http://pelias-placeholder-service:3000/"
interpolationHost: "http://pelias-interpolation-service:3102/"
libpostalHost: "http://pelias-libpostal-service:8080/"
pipHost: "http://pelias-pip-service:3102/"

placeholderStoreURL: "https://s3.amazonaws.com/geocodeearth-pelias-data/placeholder/store.sqlite3.gz"
