# override this to use external elasticsearch
elasticsearch:
  host: "elasticsearch-service"
  port: 9200
  protocol: "http"

# Whether the API service should be externally accessible
# Set this to true if you want to, for example on AWS, set up an ELB for the API
externalAPIService: false
# whether this ELB should be internet facing or private (default private)
privateAPILoadBalancer: true

## API settings
api:
  autocomplete: {}
  requests: {}

# the name of the Elasticsearch index to use
apiIndexName: "pelias"
apiAttributionURL: "http://api.yourpelias.com/attribution"

# Whether the dashboard should be set up
dashboard:
  enabled: true
  domain: null # set this to enable an ingress

placeholderHost: "http://pelias-placeholder-service:3000/"
libpostalHost: "http://pelias-libpostal-service:4400/"

libpostalEnabled: true
placeholderEnabled: true

placeholderStoreURL: "https://s3.amazonaws.com/pelias-data.nextzen.org/placeholder/store.sqlite3.gz"

interpolation:
  enabled: false
  host: "http://pelias-interpolation-service:3000/"
  pvc: {}
#    create: true
#    name: interpolation-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}

pip:
  enabled: true
  host: "http://pelias-pip-service:3102/"
  pvc: {}
#    create: true
#    name: pip-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}


# Deprecated fields
# pipEnabled: true
# pipHost: "http://pelias-pip-service:3102/"

# interpolationEnabled: false
# interpolationHost: "http://pelias-interpolation-service:3000/"
